### PR TITLE
Introduce test suites with some changes

### PR DESCRIPTION
**Pull request by zkan**
- Changed expiration month and expiration year on credit card form to dropdown and update form's style.
- Added bootstrap files for Docker container for running unit tests with WP.
- Updated developer guide: how to run tests with Docker container.
- Created tests for `Omise_Util` class.
- Created tests for `Omise` class (API wrapper).
  - Changed method type from static to public in order to easily maintain test suites.
- Revised code to follow WordPress coding standards.
- Tested with WordPress 4.4.2 and WooCommerce 2.5.2.

### CODE REVIEW

**Comment by guzzilar** [comment]
Hi @zkan, thanks for your PR.
I'll review it and give you a response as fast as I can!

I'm excited to see how test suites works with Omise-WooCommerce.
Appreciate it! :smile:

**Comment by zkan** [comment]
Thank you! @guzzilar Let us know if there's anything you'd like us to fix. :heart:

**Comment by guzzilar** [comment]
Hi @zkan 
I just pushed a `develop` branch here. Could you re-open your PR to that `develop` branch instead?
Also, I want to inform you that I'm gonna redesign our dashboard, update/add more features in Omise-WooCommerce. So, it may make a huge conflict to your pr (I saw that you also revised code style).

However, I'm really interested in your test suites stuff. I'm looking a way to just merge only test suites (to avoid merge conflict, like I said that I'm gonna redesign stuff, add more features). Do you have any suggestion about it?

**Comment by guzzilar** [comment]
@zkan also, about code indentation (for this project only 😂) , I used `real tab` instead of `4 spaces` to follow WordPress coding standards. Could you update this pr to use `tab` instead

**Comment by zkan** [comment]
@guzzilar Sorry for my late reply. I'll surely do it! :D

**Comment by zkan** [comment]
@guzzilar I should use the real tab for *.php, *.js, and *.css, right?

**Comment by guzzilar** [comment]
@zkan Hi, I decided to restructuring all code to a new one which most of them wasn't match with this old structure.

So, I would like to close this PR soon, if you have any opinions on this or want to re-open a pull request with the new structure one, feel free to make it :)

Thanks for your contribution! 👍

**Comment by zkan** [comment]
@guzzilar No worries. Thank you!

**Pull request closed without merging**
